version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: neurapay_admin
      POSTGRES_PASSWORD: your_secure_password_123
      POSTGRES_DB: neurapay_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    environment:
      - REDIS_PASSWORD=your_redis_password_123
    command: redis-server --requirepass your_redis_password_123
volumes:
  postgres_data:
